name: publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: xvfb-run -a npm test
      - name: Publish (vsce)
        if: success()
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish (ovsx)
        if: success()
        run: npx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
